---
- name: Prepare SSH config
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    #ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts_file: "{{ '/root/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['target'] }}"
  
  tasks:
  - name: get whoami
    command: whoami
    register: mystdout
  
  - name: make directory
    file:
      path: "/root/.ssh"
      state: directory
    become: yes
    become_user: root
  
  - name: For each host, scan for its ssh public key
    shell: "ssh-keyscan {{ item }}"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_host_results
    ignore_errors: yes

  - name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
    known_hosts:
      name: "{{ item.item }}"
      key: "{{ item.stdout }}"
      path: "{{ ssh_known_hosts_file }}"
    with_items: "{{ ssh_known_host_results.results }}"
