---
- name: Prepare SSH config
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['target'] }}"
  
  tasks:  
  - name: For each host, scan for its ssh public key
    shell: "ssh-keyscan {{ item }}"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_host_results
    ignore_errors: yes
    
  - name: Set up multiple authorized keys
    authorized_key:
      user: awx
      state: present
      key: "{{ item.stdout }}"
    with_items: "{{ ssh_known_host_results.results }}"
