---
- name: Ping Hosts
  hosts: all
  remote_user: ip172-18-0-41-bd49ssf466cg00f29t50
  
  tasks:
  - name: tell the host about our servers it might want to ssh to
    known_hosts:
      path: /root/.ssh/known_hosts
      name: 192.168.0.33
  
  - name: ping
    ping:
