---
- name: Ping Hosts
  hosts: all
  gather_facts: no
  
  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ /root/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['all'] }}"
  
  tasks:
  - name: For each host, scan for its ssh public key
    shell: "ssh-keyscan {{ item }}"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_host_results
    ignore_errors: yes
    
