---
- name: Prepare SSH config
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
  - name: make directory
    file:
      path: "/root/.ssh"
      state: directory
      
  - name: create empty file
    file:
      path: "/root/.ssh/authorized_keys"
      state: touch
      
  - name: create empty file
    file:
      path: "/root/.ssh/id_rsa.pub"
      state: touch
      
  - name: tell the host about our servers it might want to ssh to
    known_hosts:
      path: "/root/.ssh/known_hosts"
      name: "192.168.0.14"
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      
  - name: For each host, scan for its ssh public key
    shell: "ssh-keyscan {{ item }}"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_host_results
    ignore_errors: yes
